### ISSUE TITLE
Case sensitivity of FileFormat and FileType

### ISSUE THREAD

**Issue by reneherrero** [iho-ohi/S-101_Portrayal-Catalogue#129]
* In section 9-13.3.24 of the S-100 specs, FileFormat values are defined as all lower case.
* In section 9-13.3.25 of the S-100 specs, FileType values are defined as 'pascalCase'.

Incorrect samples can be found here: 
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/4c55c4fc85f9bd3d77fa6ac13effa64b296b60de/PortrayalCatalog/portrayal_catalogue.xml#L28
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/4c55c4fc85f9bd3d77fa6ac13effa64b296b60de/PortrayalCatalog/portrayal_catalogue.xml#L29

**Comment by DavidGrant-NIWC** [comment]
There are some minor discrepancies between the spec and the actual S-100 schemas; the PC has to conform to the schemas rather than the spec. The S-100 schemas are available here: https://schemas.s100dev.net/

In particular, see https://schemas.s100dev.net/schemas/S100/5.0.0/S100PC/20220705/S100PortrayalCatalog.xsd

![image](https://user-images.githubusercontent.com/62906211/200414469-3363d395-ffee-461b-bb4b-f70c3f054837.png)

![image](https://user-images.githubusercontent.com/62906211/200414282-4eb55138-bfb6-438a-ac59-eb6405630316.png)

To address the discrepency between the spec and schema you would need to submit an S-100 change proposal: https://iho.int/en/basic-wg-documents-8
![image](https://user-images.githubusercontent.com/62906211/200415640-c36c5110-9108-49dc-85f5-990ed3e22f4b.png)

**Comment by reneherrero** [comment]
Understood.  Thanks for pointing that out @DavidGrant-NIWC
