### ISSUE TITLE
INFORM01 symbol should be displayed when feature itself contains information

### ISSUE THREAD

**Issue by JoeMassey-WRSystems** [iho-ohi/S-101_Portrayal-Catalogue#174]
Currently the portrayal catalog checks for an association to NauticalInformation when determining whether to display the INFORM01 symbol.  It is possible to encode this information in the feature itself using the _information_ complex attribute.

The portrayal catalog needs to be updated to check for the information on the feature itself in addition to the NauticalInformation association.

**Comment by DavidGrant-NIWC** [comment]
It may also need to check for _information_ on instances of associated InformationTypes. The current FC binds the _information_ complex attribute to the following Information types: _NauticalInformation_, _NonStandardWorkingDay_, and _ServiceHours_.

**Comment by JoeMassey-WRSystems** [comment]
The _UpdateInformation_ feature type contains the mandatory complex attribute _updateDescription_, which contains the _text_ attribute.  Since _updateDescription_ is mandatory, this means _UpdateInformation_ will always unconditionally show the _INFORM01_ symbol.

Since there is no symbol defined for _UpdateInformation_ yet, do we want to display _INFORM01_ for it?

**Comment by DavidGrant-NIWC** [comment]
I think it should show `INFORM01` if the `information` attribute is present. I don't think it should show `INFORM01` based on the presence of `updateDescription` (this could change in a future PC revision).

> Since there is no symbol defined for UpdateInformation yet, [...]

There are symbols defined (`CHRVDEL1`, etc.), the rules just aren't assigning them yet because there is ongoing discussion in the PSWG about how `UpdateInformation` is supposed to work.

**Comment by mikan66** [comment]
Concur, the full details of _UpdateInformation_ implementation will be addressed at a later time (future PC version).
