### ISSUE TITLE
Incorrect reference to css file in DRFSTA02.SVG

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#185]
PC 1.1.0. There is incorrect reference to SVGStyle.css in the DRFSTA02.SVG file:
`<?xml-stylesheet href="SVGStyle.css" type="text/css"?>`
As a result, it is depicted as:
![image](https://user-images.githubusercontent.com/106175259/226899462-9dc5ae3e-f2a2-4876-b7b2-61ff987e538b.png)
It should be replaced with href="daySvgStyle.css"

**Comment by DavidGrant-NIWC** [comment]
Fixed.

Note that using an invalid value for the stylesheet shouldn't affect an ECDIS because the ECDIS will replace the stylesheet reference with the value of the `css` attribute of the `palette` entry of the `colorProfile`.
![image](https://user-images.githubusercontent.com/62906211/226929657-48d63de0-3ad8-4b3d-bb80-fde4f9c07c52.png)
