### ISSUE TITLE
HELIPD02 has incorrect priority when used as centered area symbol

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#208]
@TDYCARHugh reported:
> Lua portrayal AirportAirfield.lua the HELIPD02 point symbol should be drawn at priority 12 but it is currently at 6 when drawn on a surface.

**Comment by DavidGrant-NIWC** [comment]
Updated to 12, but I'm not sure that's correct since it's taking the place of the AIRARE02 pattern, which has a priority of 6. The H is just an annotation of the `AirportAirfield`, as opposed to an `AirportAirfield` of type point where the `HELIPD02` symbol is the sole representation of the feature.

Note that even after updating the Helipad symbol can be obscured by a runway:
![image](https://user-images.githubusercontent.com/62906211/228676552-817b4fb2-1630-405c-8990-364c53b4cf32.png)

Runways have a priority of 15, so they can obscure a lot of things - in the pic below the `AIRARE02` pattern is being obscured, as is a portion of the `LightAllAround`:
![image](https://user-images.githubusercontent.com/62906211/228678217-0fde9904-6f66-464a-9714-7bf4b5d86c20.png)

@alvarosanuy are you ok with this implementation?

**Comment by alvarosanuy** [comment]
To be consistent with S-52 AIRARE, **Airfield** features of type Point should have Priority=12 and of type Surface Priority=6.

**Runway** features of type Surface and Point, have larger display priority to make sure the sit on top of **Airfield**

 **Airfield** of type point obscured by **Runway** of type area shouldn't be a problem because it does not seem to be  a logical encoding scenario (all the runways should live within the area covered by the Airfield point symbol and therefore generalised out).

**Comment by DavidGrant-NIWC** [comment]
> Runway features of type Surface and Point, have larger display priority to make sure they sit on top of Airfield

Will revert to priority 6, noting that for an `AirportAirfield` with surface geometry the distinction between heliport or airport may be partially or completely obscured by one or more `Runway` features.
