### ISSUE TITLE
Incorrect label for Local Magnetic Anomaly

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#214]
I'm sorry, I sent my comment for PC 1.1.0 after deadline, however, issues come during the implementation of PC. 
Now we have run across with an incorrect label of Local Magnetic Anomaly. 
For example, from the clause 27.119 of DCEG the magnetic anomaly value attribute is equal to 30.3 minutes, it is depicted as:
![image](https://user-images.githubusercontent.com/106175259/228510595-1c35a3ff-438c-4b23-a99f-586bb1b0ed5e.png)

The label depicts degree symbol, but the unit of the magnetic anomaly value attribute is minutes according to the clause 27.119 of DCEG.
it means we have to EITHER convert the magnetic anomaly value to degrees before the drawing
![image](https://user-images.githubusercontent.com/106175259/228513140-188bd588-bd42-41b9-8a6a-966d77461ea9.png) 
OR show "'" minute symbol instead of degree symbol in the label.
![image](https://user-images.githubusercontent.com/106175259/228512200-c64983ec-22a2-4200-85fe-e76be3e16e60.png)

**Comment by alvarosanuy** [comment]
Hi all, 

At the moment PC goes against the instructions for the attribute (Units is minutes not degrees). Having said this please refer to S-4 B-274.1
![image](https://user-images.githubusercontent.com/70189016/228678286-c597568b-b70b-4cfe-bd4f-3f19923b7a79.png)
 

Current guidance is to encode a  Local magnetic anomalies only when larger than 3 degrees. This guidance is also included in section 4.2 of the DCEG.

Based on this and the examples I am of the opinion VALLMA should be expressed in Degrees and not in minutes.

Having said that, it contradicts what’s is currently stipulated for this attribute (VALLMA) in S-57. Please note that VALLMA is not currently be used by S-52.

**Needs to be discussed by the DCEG subWG.** If we were to use minutes as Units for VALLMA and Local Magnetic Anomalies should only be depicted when >3 degrees, then the portrayal would be 180.0’ (as an example for 3 degrees). It does not make sense to me.

**Comment by JeffWootton** [comment]
I agree with Alvaro.  The unit of measurement (minutes) for the S-101 attribute magneticAnomalyValue has been taken directly from the corresponding S-57 attribute VALLMA without question or discussion.  It does not make sense to me that a mariner will need to do a mathematical conversion (of a value > 180 as Alvaro says) from minutes to degrees before applying the variation to their magnetic compass bearing, noting (again as Alvaro says) that the anomaly should not be charted unless it is greater than 3 degrees.  The other significant factor for me is that the examples of local magnetic anomaly in S-4 quote the anomaly in whole degrees only.

I will raise a GitHub issue on this for discussion within the DCEG Sub-Group, with the intention of an agreement to amend the units of measure for magneticAnomalyValue from minutes to degrees for S-101 Edition 1.2.0.

**Comment by mikan66** [comment]
For PC 1.1.1, I will leave the implementation "as-is" and leave this issue open for 1.2.0.

**Comment by DavidGrant-NIWC** [comment]
https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/63

**Comment by alvarosanuy** [comment]
The symbolization shown above for Curve and Surface does not match current S-52 entries in the LUT.

Having said this, I believe that, for Surfaces, CHGRD should be replaced with CHMGD colour

**Curves** - I imagine the 'arrow' symbol (LOCMAG01) would sit to the left side of the middle point of the line? Otherwise a new complex line will have to be created. How is it done today in S-52??
 
**Areas Plain Boundaries** - Propose replacing SY(LOCMAG51);LS(DASH,1,CHGRD) with SY(LOCMAG51);LS(DASH,1,CHMGD). LOCMAG51 will sit in the middle of the area.

**Areas Symbolized Boundaries** - Propose replacing SY(LOCMAG51);LC(NAVARE51) with SY(LOCMAG51);LC(CTYARE51). LOCMAG51 will sit in the middle of the area.

I will add a new PsWG Github issue to discuss this.

**Comment by mikan66** [comment]
See #254 for correction, but the values are very hard to read in this font.
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/6defbd17-705d-4f46-900f-5b0c40a1b680)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/c8d5440d-8bd8-4b7c-bec6-92d0d7a748d7)

**Comment by mikan66** [comment]
CHMGD is much easier to read.  The center symbol behavior I'll have to discuss with Dave. 
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/9485f5bb-82e8-4596-9ffb-6a1f5a135b67)

**Comment by DavidGrant-NIWC** [comment]
* The info symbol ("i") was shown because the feature in the test dataset has an "INFORM" attribute ("Reported locally"), and Mikan had "Highlight info" selected.
* The LOCMAG51 symbol was not visible in the original screenshot because it was offset outside of the features geometry.
  * The LOCMAG51 symbol has a large offset (I assume to move it from the center of the screen where it can distract from the ship symbol).
  * Zooming in on the area will cause the symbol to appear.
  * The test dataset should probably use a more representative (larger) area geometry for the feature.

Here's a pic with the pivot point of the symbols shown in red. I've zoomed in just far enough to cause the symbol to appear in the area:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/9f3fad46-5856-45c3-84a4-b088def14ae6)

**Comment by alvarosanuy** [comment]
> * The test dataset should probably use a more representative (larger) area geometry for the feature.

Agree - Please request update to @TomRichardson6


> * You may want to consider also using a large offset on the text, so it's aligned with the symbol.

Makes sense. Please, for Surfaces, proceed and provide the label the same vertical offset that the arrow.

I have updated https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/148 to request PsWG support to amend the colour of magnetic labels from CHMGF to CHMGD.

**Comment by TomRichardson6** [comment]
Noting the request from @alvarosanuy TDS0004 Edition 6 now contains a much larger surface feature. Please let me know if any further edits are required. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0004/6

**Comment by DavidGrant-NIWC** [comment]
This issue pertains to the value of the label; other changes should have separate (new) PC issues. That said, I went ahead and made the following changes for 1.1.2 under this issue because they are related to, or correct previous changes made under this issue:
- [x] Changed viewing group of labels from 30 (Current velocity) to 27 (MagVar, Swept Depth).
- [x] Changed color of labels to CHBLK (every text instruction I checked in S-52 uses CHBLK). Label color can be addressed in PC 1.2.0 via https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/148 if desired.
- [x] Modified text offset for label on LOCMAG51 so that the location matches location of labels on LOCMAG01

|Plain Boundaries|Symbolized Boundaries|
|:---:|:---:|
|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/7e8b0c36-b567-468e-ab54-87dedc9b2e13)|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/17ecc019-ceeb-481f-9f53-d17cae675882)

**Comment by mikan66** [comment]
RELATED discussions (Gap analysis 19OCT23 Row 66): DCEG: Amended unit of measure for attribute magnetic anomaly value from minutes to decimal degrees., DCEG 27.121: MAGNETIC ANOMALY VALUE. The value of the deviation from the normal magnetic variation. (Adapted from S-57 Edition 3.1, Appendix A – Chapter 2, Page 2.228, November 2000)
