### ISSUE TITLE
SNDFRM04 : GetSpatialAssociation or GetFlattenedSpatialAssociations ?

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#247]
To detect if a sounding must be symbolized by the low accuracy symbol (SOUNDGC2 or  SOUNDSC3), the lua rule SNDFRM04 check 
the accuracy of the direct spatial objects by GetSpatialAssociation function (point , multi points for point objects , curve or composite curve for line objects, or surface for area objects.
=> local spatialQuality = feature:GetSpatialAssociation():GetInformationAssociation(unpack(sqParams))

this means that the complex geometry (composite curve or surface) must be qualified taking account the quality of its simple spatial objects (curves) , is it the case  ? ((DCEG rule ? )
Or it will be safer to call GetFlattenedSpatialAssociations in this SNDFRM04 ?
Pol

**Comment by DavidGrant-NIWC** [comment]
I don't think this is a portrayal catalog issue. Perhaps @alvarosanuy or @jeffwootton want to provide feedback?

I don't believe SNDFRM04 is ever called to apply a sounding value to a surface geometry:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/98c93cff-8aa5-49c3-b7bb-76de063740df)

For points / multipoints there can only be a single associated `SpatialQuality`, so the concern doesn't apply.

For curves, the implementation matches the S-52 CSP, but perhaps this case could be clarified in the DCEG so that producers know to associate `SpatialQuality` with the geometry when a low-accuracy sounding value is provided.
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/5b474dc0-0f55-446a-9a87-3dc7d51c627d)

**Comment by plebihan29n** [comment]
1- Agree to consider that the issue is a production issue but the decision  could have consequence to this portrayal rule.
2- SNDFRM04 is apply to Area Obstructions for example.
3- "Get the spatial object" from S-52 must be considered to consult all spatial components , means to go through every edges of the obstruction when this is a line or area => In consequence The S-101 SNDFRM04 doesn't match S-52 if the linear object is associated to a composite curve and if this composite curve doesn't reflect the quality of its curve components.

**Comment by DavidGrant-NIWC** [comment]
1. Agreed.
2. Yes, but the DCEG does not allow `SpatialQuality` on the surface geometry, and S-52 does not evaluate each spatial component of the surface geometry (see item 3).
3. S-52 is explicit when individual components should be evaluated. See the example below (noting that soundings are not symbolized while evaluating each curve segment). Continuation C (surface geometry) doesn't evaluate the components individually.

    If you think this is an error in S-52 SNDFRM04 (e.g., it should loop over the spatial components) then it should be addressed with the ENCWG or the PSWG as a change to S-52. If a change is made, then in my opinion we should add the low accuracy symbol if any component (including the parent) has low accuracy.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/dc42f08c-3500-4aca-901e-d44a2695f9bf)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/31f51cc2-c57f-45d7-b360-a68b7d11f7db)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/96ee6edc-9eba-43a1-af12-0233c777dfa2)
