### ISSUE TITLE
PortrayalAPI.lua caches issues

### ISSUE THREAD

**Issue by halset** [iho-ohi/S-101_Portrayal-Catalogue#257]
In PortrayalAPI.lua, there are some caches for features, spatials and informations.

Does this mean that the feature ids and spatial ids should be unique across different data sets? I used the FRID as the feature id, but they are not globally unique. Should I use FOID or something else instead? Is this limitation described in the S-100 documentation?

Or is the complete Lua runtime stack expected to be reset for every new data set that is to be drawn? 

If the Lua runtime stack is not to be reset for every new data set, is there some way to evict old entries from the caches or perhaps clear the caches? Or will the caches just hold on to everything and leak memory?

**Comment by DavidGrant-NIWC** [comment]
See S-100 5.0 13-8 para. 7:

_Many of the standard script functions accept a featureID, informationTypeID or spatialID parameter. The host must ensure that these various ID parameters uniquely identify a single instance among all datasets across all product types to be used by the host during a scripting session. Since each type of ID is a string, one way to accomplish this is by prepending the relevant information to the ID; for example, "S101.101US003DE01\_\_.000.F1" to identify the first feature in the referenced S-101 dataset._

> Or is the complete Lua runtime stack expected to be reset for every new data set that is to be drawn?

That's what we currently do in our testbed. We also prepend the type of information to the value of the ID to ensure unique values within the dataset. You can see the values we use for the various ID's in the pick report when the "bug" symbol is on:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/4cf5648d-3466-4338-9096-18ff1851cd83)

As long as the values are unique to the session, and you can associate each value to an element from your SENC then it should work correctly.

**Comment by halset** [comment]
Thanks. Will make ids globally unique and make sure to reload the stack often enough.

**Comment by halset** [comment]
Thank you. I am already doing the portrayal cache, but I should probably re-visit it to make sure it is correct.

**Comment by halset** [comment]
Perhaps it should be a way to reset the caches inside the Lua files from outside of Lua without re-loading the complete Lua runtime. Either with a separate method or in the beginning and end of `PortrayalMain`. That way the Lua runtime can live longer without leaking memory.

**Comment by DavidGrant-NIWC** [comment]
> [...] reset the caches inside the Lua files from outside of Lua [...]

That would require an extension to Part 13 or Part 9a, which I don't think is appropriate for something that is an implementation detail (the caches aren't part of the model). I'm also not sure that it would have any meaningful impact on performance.

On an i5-8350U (it's pretty slow) re-loading the runtime takes about 5ms in our implementation. Initializing the context parameters adds another 10-20ms. Have you measured the performance hit of re-loading your runtime? You could compare clearing the portrayal caches at the end of PortrayalMain (line 7-119 in main.lua) vs re-loading.

Some suggestions:
* Use two runtime instances and double buffer their usage.
* Are you using a spinning hard drive?
  * Switch to an SSD.

**Comment by halset** [comment]
We are building in support for S-101 portrayal in a multi user java server application. We are using an optimized version of Rembulan that is a Lua implementation in Java. However, it is still slower than native Lua. We also use lots of threads with their own Rembulan/Lua state for rendering tiles using S-101 portrayal. 

We should probably try with native Lua, but doing that over JNI in a multitreaded/multicpiarchitecture way is not straight forward either.

> Use two runtime instances and double buffer their usage.

We use one pr thread. Just changed it to a soft reference so that they can be GCd away when memory is tight. Should perhaps change to a separate thread pool to not starve the system when under heavy load.

> Are you using a spinning hard drive? Switch to an SSD.

We are on SSD.

**Comment by DavidGrant-NIWC** [comment]
It seems like the issue is with instantiating a JVM instance rather than Lua. Some options:

#### Reset the state (possibly via persist/restore)
https://stackoverflow.com/questions/35435234/lua-reseting-the-state-of-a-script-without-reparsing-it

I'm not sure that this is possible since I haven't looked at Rembulan and we haven't tried this in our test bed.

#### Use a native implementation
As you described. This would significantly reduce your memory usage (don't know if that's an issue for you...) This is essentially what we do in our test bed (we use LuaJIT from C#).

#### Modify the PC to your liking
You could modify PortrayalAPI.lua when the PC is installed in your system and add a function to clear the caches. Subsequent updates to the PC may break your implementation, but since I assume you have easy access to your server it shouldn't be a big deal to update.

#### Use an undocumented function
An undocumented function could be added to the S-101 PC. ConvertToJSON() is an existing example. Since it's undocumented there's no guarantee that the interface won't change, or that the function will be available in future PC's or in the PC's of other products which use Lua portrayal.

You could check for the existence of the function and if it's not present you could fall back to modifying your local PC install. If you want to go this route, then either submit a pull request or open a new issue requesting the undocumented function.

#### Submit an S-100 change proposal
Add a standard function to Part 13 of S-100 (something like `13-8.1.3.5 void ClearCaches()`). This is an extension so it wouldn't be available until S-100 6.0, which doesn't help much right now. If we add an undocumented function now this could provide a path to required support in all Lua PC's.

We would also need to add text describing how/why/when this should be used.

**Comment by halset** [comment]
> It seems like the issue is with instantiating a JVM instance rather than Lua. Some options:

Thank you for good suggestions. It is working pretty well after using soft references for the lua runtime and using data set name as part of the feature id. So thanks for those hints. I will try to investigate with native lua and/or some kind of `ClearCaches` to improve further. Instanciating the JVM is not the issue as it is running all the time.
