### ISSUE TITLE
Some labels are hard to read

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#311]
Do these match S-52?

If not, label as bug and fix, otherwise work with PSWG to resolve.

### `SpanFixed`
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/68e83c3d-7e40-4828-a3d1-956c5039e083)

### `CableOverhead`
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/63d9f9d1-6fcb-4bbd-994a-ae76ba8bb5e1)

**Comment by TomRichardson6** [comment]
To answer the question, I think CableOverhead is consistent with S-52. But SpanFixed and SpanOpening are not consistent with BRIDGE. I think this may relate to the use of LocalOffset or LinePlacement see examples below. 

Looking at implementations some OEMs have used halos and italics here which help distinguish text. Also, the CHGRD looks much lighter so the text is more readable.

Looking back at the S-52 LUTs it seems that for bridges a Y Offset Parameter has been used in addition to the X Offset. Where the point symbol is not shown I wonder why the X Offset is needed anyway. 

It does seem that CableOverhead uses LocalOffset rather than Line Placement. SpanOpening has instructions for both which, I assume explains the text in the top of the first image which is offset above the line as its getting offset twice.

Overall seems like one for the PSWG. Clearly the S-52 syntax does not map cleanly to Part 9a when offsets and placement are involved. So that adds complexity.

See relevant TE instructions and Lua rules below.

BRIDGE
TE('clr op %4.1lf','VERCOP',3,1,2,'15110',1,1,CHBLK,11)

SpanFixed(Curve)
('LinePlacement:Relative,0.5;FontSize:10;FontColor:CHBLK')

SpanOpening(Curve)
('LinePlacement:Relative,0.5;FontSize:10;FontColor:CHBLK')
('LocalOffset:3.51,0')

CBLOHD
TE('sf clr %4.1lf','VERCSA',3,1,2,'15110',1,0,CHBLK,11)

CableOverhead (Curve)
LocalOffset:3.51,0;FontSize:10;FontColor:CHBLK

S-52 Syntax (if needed)
TE (‘FORMAT’ , ‘ATTRIB1,ATTRIB2,…’, HJUST, VJUST, SPACE, CHARS, 
XOFFS, YOFFS,COLOUR, DISPLAY);

**Comment by alvarosanuy** [comment]
I believe all text strings for 'Clearances' should have both, Vertical and Horizontal offsets. Vertical offsets help avoid clashing with Curves oriented East-West and horizontal offsets with those oriented N-S (beyond avoiding central symbols when they exist). Of course, it's not possible to cater for all possible Curve orientations.
I recommend we include vertical and Horizontal offsets to cover for central symbols and N-S & E-W curves' orientations. Offset value (H & V) could be identical and should position the text a bit closer than what's shown in screenshot 1 above (first example from the top). 
Not sure about the differences between LinePlacement and LocalOffset. Therefore, I'm happy for NIWC to work with their preferred option and upload screenshots of the outcomes.

- For 'safe vertical clearances' I wonder why we use black/CHGRD and not Magenta text as per S-4?

Clearances also apply to Overhead Pipelines. Do they portray ok?

**Comment by DavidGrant-NIWC** [comment]
> Clearances also apply to Overhead Pipelines. Do they portray ok?

Those are using an X,Y offset of 3.51, 3.51:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/04d01a9f-6c05-4123-a39d-859d989d0d0a)

**Comment by alvarosanuy** [comment]
Looks Ok to me.

**Comment by TomRichardson6** [comment]
I also think that looks ok; therefore I support the recommendation from @alvarosanuy to have both vertical and horizontal offsets for all clearances. This addresses the issue and is consistent. 

In terms of S-4 B-382, I assume that this is because we have the text legend to distinguish these values. Suggest raise a separate issue for that within PSWG as it may need to consider broader S-4 compliance. But not for 2.0.0.

**Comment by DavidGrant-NIWC** [comment]
Agree with Tom's assessment. A couple comments though:

> [...] I assume explains the text in the top of the first image which is offset above the line as it's getting offset twice.

Assuming one unit of offset (equivalent to 3.51mm), an offset up with vertical alignment = Bottom leaves 3.51mm of space between the text and the line. When offset down with vertical alignment = Bottom, there is 3.51mm between the bottom of the text and the line, which leaves very little white space. If we wanted a consistent amount of space between the text and the line then the vertical alignment would have to change.

> It does seem that CableOverhead uses LocalOffset rather than Line Placement. SpanOpening has instructions for both which [...]

The default for the line placement is at the geographic center of the line, so it's not strictly necessary to issue a LinePlacement instruction. I'll remove the LinePlacement instructions from SpanFixed and SpanOpening.
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/cee15e19-89c7-4c49-ad9e-4f9db74dba5c)

**Comment by alvarosanuy** [comment]
Use X,Y offset of 3.51, 3.51 then? No LinePlacement instructions.

**Comment by DavidGrant-NIWC** [comment]
Adjusted the placement for `CableOverhead`.
Placement was not adjusted for `SpanOpening` because the Y offset is used to stack the open and closed clearance values.
Placement for `SpanFixed` was adjusted to match S-52 (corrected a bug).

Note that text placement will all be affected by `featureName` since an object name can be added to any feature regardless of attribution. Suggest revisiting this on a case-by-case basis once supporting test data is available. At minimum, we need all clearance values populated along with feature name.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/154cdcea-7e96-4a0e-a849-814a24845f0b)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/67769b18-5923-4cf6-bd99-9b74223e0e7e)
