### ISSUE TITLE
Check clearance text open and closed for bridges

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#315]
For example from S-52, there are two text values

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/bb882b3d-2a6d-4cef-b91e-b3d0f6aff296)

**Comment by alvarosanuy** [comment]
When it's possible for 2 labels to display at the same time (and from the same location), we should offset them so they do not overlap.
They can have the same xOffset but the yOffset should be double.

**Comment by mikan66** [comment]
@alvarosanuy , The porting from S-52 for BRIDGE into S-101 that use symbol "BRIDGE01", has the clearance text processed as part of feature "SpanOpening", (DCEG v1.2.0, section 6.8 Span opening), only.  Both open and closed clearance text is processed and displayed as clearance CLOSED over clearance OPEN, similar to the S-52 rule above.  If these conditions are correct, I can close this issued.

**Comment by DavidGrant-NIWC** [comment]
While this issue can be closed, there is still an issue:

* In S-52 `BRIDGE` doesn't display `OBJNAM` when two clearance values are displayed.
  * It does when only the `VERCLR` is displayed.
* In S-101, any feature can display a name via `featureName` (or less likely, via `TextPlacement`)
  * We need to ensure these strings don't overwrite one another, without also reserving a lot of empty space.
  * Another consideration is that stacking text three lines high may not be very readable.

The issue applies not just to `Bridge`, but to any feature that displays text and has the `featureName` attribute. We really need test data to evaluate some of these considerations.

**Comment by alvarosanuy** [comment]
I'll as Matt to encode some opening **Bridge** examples with both clearances (closed & open) populated + **featureName**

**Comment by DavidGrant-NIWC** [comment]
Anything that potentially has lots of labels associated with the symbols would be good to test, especially when the symbols are large. Lighted beacons / buoys, etc.

**Comment by MatthewCraggs** [comment]
@DavidGrant-NIWC 
[101AU00315_315.zip](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/14273942/101AU00315_315.zip)
Hi Dave, I have attached a 1.2.0 ENC with a Bridge_L and **textplacement** features (38.106459s 144.363398e). unfortunately I have some issues with creating an area bridge with **textplacement** features. A request for help from caris has been made. 
Hopefully this helps for a start, I will reupload when the previously mentioned error is remediated .

**Comment by DavidGrant-NIWC** [comment]
> @DavidGrant-NIWC [101AU00315_315.zip](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/14273942/101AU00315_315.zip) Hi Dave, I have attached a 1.2.0 ENC with a Bridge_L and **textplacement** features (38.106459s 144.363398e). unfortunately I have some issues with creating an area bridge with **textplacement** features. A request for help from caris has been made. Hopefully this helps for a start, I will reupload when the previously mentioned error is remediated .

Thanks, I think we'll be able to use this to start with.

I do see though that there are actually three bridges encoded at that location:
Bridge:7821 (CompositeCurve) - associated with three text placement features ("test test test" @ 45deg 6mm; Bridge name @ 0deg 0mm; and Bridge name @ 225deg 20mm)
Bridge:7823 (no geometry)  - associated with the two pylons
Bridge:7824 (no geometry) - associated with the span opening

* Bridge:7823 and Bridge:7824 shouldn't be present.
* There can only be one TextPlacement per Bridge.
* The pylons and span should be associated to Bridge:7821

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/97567077-bdfe-4d41-8995-d50935e7f1b4)

**Comment by MatthewCraggs** [comment]
Interesting. In compilation I created 1 span opening, 2 span fixed, 2 pylons, 1 bridge and 3 text points (Alvaro wanted to see the effect of different combinations). I will pass this information on to Hugh and Mary at Caris as it may be related to the issues I was having with the Bridge_A conglomeration.

**Comment by DavidGrant-NIWC** [comment]
Hmm, there doesn't appear to be any `SpanFixed` at that location. Also, here's some encoding errors you might want to pass along:

[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7799 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7798 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7788 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7783 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7776 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7768 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7759 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7749 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|7748 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7715 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7540 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7459 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7428 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7423 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7421 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7339 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7268 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|7059 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6994 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6947 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6900 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6888 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6812 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6710 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6679 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6479 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6453 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6358 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6335 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6286 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6216 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6215 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6157 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|6095 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|5973 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|5858 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|5375 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|5099 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|4968 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|4474 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|3955 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|3833 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|3738 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|3576 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|3231 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|3183 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|3182 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Obstruction ID=Feature|2860 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2262 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2243 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2225 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2224 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2204 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2203 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2199 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2183 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2164 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2130 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2115 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2100 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2085 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2073 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2071 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2058 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2055 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2042 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2039 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2024 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|2008 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1965 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1951 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1937 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1923 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1908 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1830 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1757 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1740 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1577 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1473 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1457 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1456 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1455 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1441 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1440 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1424 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1408 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1392 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1287 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1269 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1253 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|1236 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|802 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for Wreck ID=Feature|715 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|677 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|670 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|662 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|655 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|647 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|639 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|630 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|622 returned.
[string "S100Scripting"]:14: Neither valueOfSounding or defaultClearanceDepth have a value.  Default symbology for UnderwaterAwashRock ID=Feature|613 returned.
[string "S100Scripting"]:14: Not Implemented: No symbology defined in S-52 for TextPlacement.  Default symbology for TextPlacement ID=Feature|139 returned.
[string "S100Scripting"]:14: Not Implemented: No symbology defined in S-52 for TextPlacement.  Default symbology for TextPlacement ID=Feature|138 returned.
[string "S100Scripting"]:14: Not Implemented: No symbology defined in S-52 for TextPlacement.  Default symbology for TextPlacement ID=Feature|137 returned.
[RestrictedArea:Feature|6463]: invalid number of restriction attributes: 0 (expected 1:∞)
[MagneticVariation:Feature|5865].referenceYearForMagneticVariation="2021" is invalid for TruncatedDate
[LightAllAround:Feature|836].periodicDateRange.dateStart="--12" is invalid for TruncatedDate
[LightAllAround:Feature|836].periodicDateRange.dateEnd="--05" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|828].periodicDateRange.dateStart="--12" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|828].periodicDateRange.dateEnd="--05" is invalid for TruncatedDate
[LightAllAround:Feature|820].periodicDateRange.dateStart="--12" is invalid for TruncatedDate
[LightAllAround:Feature|820].periodicDateRange.dateEnd="--05" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|812].periodicDateRange.dateStart="--12" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|812].periodicDateRange.dateEnd="--05" is invalid for TruncatedDate
[LightAllAround:Feature|716].periodicDateRange.dateStart="--12" is invalid for TruncatedDate
[LightAllAround:Feature|716].periodicDateRange.dateEnd="--05" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|706].periodicDateRange.dateStart="--12" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|706].periodicDateRange.dateEnd="--05" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|544].periodicDateRange.dateStart="--11" is invalid for TruncatedDate
[SpecialPurposeGeneralBuoy:Feature|544].periodicDateRange.dateEnd="--07" is invalid for TruncatedDate
[LightAllAround:Feature|535].periodicDateRange.dateStart="--11" is invalid for TruncatedDate
[LightAllAround:Feature|535].periodicDateRange.dateEnd="--07" is invalid for TruncatedDate
[SoundingDatum:Feature|136]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|133]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|131]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|129]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|128]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|127]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|124]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|122]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|121]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|119]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|116]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|115]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|114]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|109]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|107]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|106]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|105]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|104]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|101]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|97]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|95]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|94]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|91]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|90]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|87]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|86]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|83]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|82]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|79]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|78]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[DataCoverage:Feature|76]: invalid number of optimumDisplayScale attributes: 0 (expected 1:1)
[DataCoverage:Feature|76]: invalid number of minimumDisplayScale attributes: 0 (expected 1:1)
[DataCoverage:Feature|76]: invalid number of maximumDisplayScale attributes: 0 (expected 1:1)
[SoundingDatum:Feature|75]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|72]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|71]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|69]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[DataCoverage:Feature|65]: invalid number of minimumDisplayScale attributes: 0 (expected 1:1)
[SoundingDatum:Feature|64]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|63]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|61]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[DataCoverage:Feature|59]: invalid number of minimumDisplayScale attributes: 0 (expected 1:1)
[SoundingDatum:Feature|53]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|48]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|46]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[DataCoverage:Feature|44]: invalid number of minimumDisplayScale attributes: 0 (expected 1:1)
[SoundingDatum:Feature|42]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|41]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|37]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|34]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|31]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|30]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|29]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|28]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|23]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[DataCoverage:Feature|21]: invalid number of minimumDisplayScale attributes: 0 (expected 1:1)
[SoundingDatum:Feature|20]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|18]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|17]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|16]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|14]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|13]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|10]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|9]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|8]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|6]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|5]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|4]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|3]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|2]: invalid number of verticalDatum attributes: 0 (expected 1:1)
[SoundingDatum:Feature|1]: invalid number of verticalDatum attributes: 0 (expected 1:1)
Skipping validation of required feature associations because of large number of issues with S-101 FC
[SpatialQuality:Information|13].qualityOfHorizontalMeasurement="2" is invalid for Enumeration
[SpatialQuality:Information|12].qualityOfHorizontalMeasurement="3" is invalid for Enumeration
[SpatialQuality:Information|11].qualityOfHorizontalMeasurement="6" is invalid for Enumeration
[SpatialQuality:Information|10].qualityOfHorizontalMeasurement="9" is invalid for Enumeration
[SpatialQuality:Information|9].qualityOfHorizontalMeasurement="1" is invalid for Enumeration

**Comment by DavidGrant-NIWC** [comment]
There are two DataCoverage features. One covers the entire dataset and has no attributes (no max/min/optimumDisplayScale). The other covers part of the chart and does have attributes:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/d0716656-2928-4c35-9395-63fc92934f2b)

**Comment by DavidGrant-NIWC** [comment]
* As Mikan noted, the clearance text is associated with a span, whereas the name is associated with a bridge
  * These two features are likely to have different geometry, so the labels should already be offset.
* Even if they do conflict:
  * the bridge name can be repositioned via TextPlacement.
  * the bridge name and clearance text are in different text groups, so they can be turned on/off independently.

Closing as OBE.
