### ISSUE TITLE
“system” attribute flare bearing [PSWG #161, Row 10]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#361]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/f0587197-7000-4acb-bbd1-bba700d0983d)

**Comment by mikan66** [comment]
S-101PT13 decision: Bring back CSP, revert other changes associated with removal of CSP and re-test CSP.

**Comment by alvarosanuy** [comment]
HI @mikan66  - By reading the latest DCEG, the population of 45 degrees or 45/135 degrees on coincident lights, is to be done by the Production Tool (e.g. CARIS). Consequently, the PC Rule should either point the flare at 45 degrees when the attribute is empty or towards the direction populated in the **flareBearing** attribute (either auto populated by the Prod. tool or modified by the cartographer).
Is this not what you guys had in PC 1.3.0??
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/70189016/bf0d75df-8600-4663-9378-3e38f2011743)

**Comment by mikan66** [comment]
@alvarosanuy, 1.3 had: if flareBearing defined, rotation = feature.flareBearing.

**Comment by alvarosanuy** [comment]
@JeffWootton - @DavidGrant-NIWC  Is the wording of DCEG 1.4.0 in accordance with Decision made at S101PT13?
It looks it continues referring to the attribute as a 'system' one and requires Production Tools to manage coincident lights. Equally the software could populate the default angle when no coincident angles exist.... Portrayal rule would only say 'point the flare' as per flareBearing value (this will cover manual updates by cartographers). Just trying to make sense between what is currently in PC 1.3.0 and what is expected for 1.4.0. Maybe is just me because I was not at the meeting during the discussion of this topic.
If we want Production tools to 'do nothing' then we can't call the attribute a 'system' attribute and the wording of the DCEG needs to be removed. Then we would make sure CSP is **fully** implement by the PC.

**Comment by JeffWootton** [comment]
@alvarosanuy you are correct. The attribute should be amended to be a feature attribute rather than a system attribute - I should have taken an action to do this at S-101PT13. It will be amended for Edition 1.4.1.

This will not impact FC development as there is no method in the FC for indicating the nature of an attribute (feature, system, ...).

**Comment by alvarosanuy** [comment]
All good, thanks Jeff.
