### ISSUE TITLE
Landmark portrayal featureName placement different for simplified/traditional

### ISSUE THREAD

**Issue by TDYCARHugh** [iho-ohi/S-101_Portrayal-Catalogue#382]
For point Landmarks the portrayal appears to be the same for simplified and not except for the placement of feature name for TOWERS15 and TOWERS05.  
Simplified has LocalOffset:3.51,3.51  and not simplified is LocalOffset:3.51,-3.51

Is this intentional?

**Comment by DavidGrant-NIWC** [comment]
It's hard to believe it's intentional, but we're just implementing the S-52 presentation. Probably should raise the issue with the ENCWG and/or PSWG to see if anything should be done. Closing for now, will re-open if directed to change the portrayal.

|Symbol|Simplified|Paper Chart|
|:---|:---:|:---:|
|TOWERS05|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/9e7007fc-3f54-401d-8f97-b1b0e28c1db8)|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/b1e479cf-d4d2-4bf3-a40c-667111765533)
|TOWERS15|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/225175e8-1adc-4015-8441-710262263217)|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/475aa9a0-10a9-4109-b406-e1e2ae100f7a)

**Comment by DavidGrant-NIWC** [comment]
Reopened, tracking https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/166

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/cf2f1387-8c8f-4d01-ae31-46fb82162820)
