### ISSUE TITLE
Virtual AIS Aid to Navigation (row 34 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#51]
Reference: 
20220422_S101 Portrayal_Consolidation of pending actions.xlsx
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/59

New symbology + Allocate feature to BASE Display

Do we use Holger's VirtualAtoN.zip to prototype or not? 
We could use existing Buoy Lateral or Buoy Cardinal rules with similar login on virtualAISAidToNavigationType.

* [x] Ensure NavHazard alert is generated (see #44)

- [x] VATON00.svg,   symbol for a general / unknown type virtual AIS
- [x] VATON01.svg ,  1 - North Cardinal, { and so on for remaining virtualAISAidToNavigationType}
- [x] VATON02.svg
- [x] VATON03.svg
- [x] VATON04.svg
- [x] VATON05.svg
- [x] VATON06.svg
- [x] VATON07.svg
- [x] VATON08.svg
- [x] VATON09.svg
- [x] VATON10.svg
- [x] VATON11.svg
- [x] VATON12.svg

**Comment by alvarosanuy** [comment]
OFFICIAL
Hi Mikan,

Yes, please use Holger’s files in Github.

Alvaro

Alvaro Sanchez | Acting Director National Charting
Australian Hydrographic Office | Maritime Geospatial Branch
8 Station Street, Wollongong
T: +61 2 4223 6506 | M: +61 434 349 674

Defence Intelligence Group | Department of Defence
[AGO Logo2]

IMPORTANT: This email remains the property of the Department of Defence. Unauthorised communication and dealing with the information in the email may be a serious criminal offence. If you have received this email in error, you are requested to contact the sender and delete the email immediately.


From: mikan66 ***@***.***>
Sent: Friday, 6 May 2022 4:25 AM
To: iho-ohi/S-101_Portrayal-Catalogue ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iho-ohi/S-101_Portrayal-Catalogue] Virtual AIS Aid to Navigation (row 34 main) (Issue #51)

EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.

Reference:
20220422_S101 Portrayal_Consolidation of pending actions.xlsx
S-101-Portrayal-subWG/Working-Documents#59<https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/59>

New symbology + Allocate feature to BASE Display

Do we use Holger's VirtualAtoN.zip to prototype or not?
We could use existing Buoy Lateral or Buoy Cardinal rules with similar login on virtualAISAidToNavigationType.

**Comment by IngaFjellanger** [comment]
1. We suggest to decrease magenta circle to a diameter of 8mm. This will improve readability of both this symbol and ECDIS rhombus.  Suggestion:  Set radius of magenta circle equal to 4 mm for all symbols of Virtual AIS Aid to Navigation features.
2. We suggest renaming symbols for Virtual AIS AtoN according to type of AtoN instead of their  values. It simplifies the handling of the symbols files and analyze drawing instruction during implementation of PC.
Suggestion: 
Rename symbols according to virtualAISAidToNavigationType
VATON01 -> VAISCAR01
VATON02 -> VAISCAR02
VATON03 -> VAISCAR03
VATON04 -> VAISCAR04
VATON05 -> VAISLAT05
VATON06 -> VAISLAT06
VATON07 -> VAISLAT07
VATON08 -> VAISLAT08
VATON09 -> VAISISD09
VATON10 -> VAISSAW10
VATON11 -> VAISSPP11
VATON12 -> VAISNDM12 where 
![image](https://user-images.githubusercontent.com/70318960/169975675-a2e64113-9edc-490e-80b8-c97596767613.png) or ![image](https://user-images.githubusercontent.com/70318960/169975714-4e5ab5b4-5bb2-431a-bc4d-08ba8ef83501.png)

**Comment by IngaFjellanger** [comment]
I deleted comment. It was  added to wrong issue. You can find it under issue 59 https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/59#issuecomment-1135528161

**Comment by mikan66** [comment]
Needs testing but all symbols incorporated, see commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/05dd031d3f7e4e0e6f6e4152cf2ac75656cd689b

**Comment by DavidGrant-NIWC** [comment]
Incorrectly assigned to viewing group 21010 (unknown object). It probably should be somewhere in the 27,000's - check with PSWG and verify all display parameters.

**Comment by mikan66** [comment]
Missing test data from 101AA00DS0021.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/b6ffad23-2de3-46d1-9302-f8cf6e017c54)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/f1081012-dd33-4bd8-9674-da8c2124e5f6)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/13dd4047-b53c-4d43-9456-ba582246398f)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/5df573a1-4f70-485a-adaf-782ce2ca82e3)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/6eac7562-7362-4660-8226-2a449719a33e)
