### ISSUE TITLE
Call Activated [Signal Generation] (row 40 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#52]
Reference: 20220422_S101 Portrayal_Consolidation of pending actions.xlsx

Reference: Copy of S-101Portrayal subWG_New Actions for S101PT8 endorsement_December2021 TR1.xlsx
PortSG-66	Signal generation	Update LightFlareAndDescription rule to add (man) when signalGeneration=3, 5, or 6 (by hand, radio activated, or call activated). For FogSignals , add "(man)" next to the symbol (FOGSIG01).

Additional discussion here: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/38

Features in question for rule revision:
![image](https://user-images.githubusercontent.com/4913543/166996162-40e59700-aa2b-4d36-81e4-3f7af5ccbbcd.png)

**Comment by mikan66** [comment]
Feedback welcome before I close the issue.  

Simulated example with signalGeneration=5 within rule LightFlareAndDescription. 
![image](https://user-images.githubusercontent.com/4913543/170123587-0565fa45-e684-4658-bec3-537157f7d135.png)

Simulated example for FogSignal rule:
![image](https://user-images.githubusercontent.com/4913543/170124896-fe7a4e45-a366-4f2f-b245-8f631ffebb73.png)

**Comment by mikan66** [comment]
(man) will add onto the end of "...W 4s".  For now, I will check in the current addition and we can re-open this issue as required.

**Comment by mikan66** [comment]
Checking this in: 
![image](https://user-images.githubusercontent.com/4913543/171433011-830a29d5-b4f2-49f2-a178-0eb64892f083.png)

Commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e9c93c29423912f15e5b95540fa6953c001d883c

**Comment by LeoKuzmin** [comment]
Unfortunately, such implementation in the LightFlareAndDescription.lua script does not allow to depict the "(man)" label for a major light. Probably, it is not quite realistic case but formally such situation could be encoded.
I suppose, this label should be added to "description" local variable in the LITDSN02.lua script.
Beside of that before to check the condition:
 if contains(feature.signalGeneration, {3,5,6}) then
we have to make sure that feature code is not LightAirObstruction, since this feature type does not contain the Signal generation attribute and the function "contains"  does not check variable as "nil" 
In addition we could check values 5,6 only that allowable for light feature.

BTW. Creation of labels for the "status" attribute values does not work in the LITDSN02.lua script too. 
![image](https://user-images.githubusercontent.com/106175259/171698261-7f781709-1b1d-4cdb-ba62-ffeeedd58efe.png)
