### ISSUE TITLE
Dredged Date (row 47 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#56]
Reference: 20220422_S101 Portrayal_Consolidation of pending actions.xlsx
![image](https://user-images.githubusercontent.com/4913543/167207344-c5f34e78-9b33-4835-897c-b9d1ef748cae.png)

Rule Update.  NOTE: Sanchez, Alvaro MR:
Display dredged date, in brackets, after depthRangeMinimumValue

See DredgedArea.lua.  Rule update with AddTextInstruction() accordingly.

**Comment by mikan66** [comment]
Example with real dredge depth and fake date.  Yes or No or formatting?
![image](https://user-images.githubusercontent.com/4913543/167194897-458da308-6a31-4733-919b-c1b4a5b227fe.png)

**Comment by mikan66** [comment]
See commit # 0658c36.  Tested with combination of real depth and fake date.

**Comment by alvarosanuy** [comment]
OFFICIAL
My input in red below

Alvaro Sanchez | Acting Director National Charting
Australian Hydrographic Office | Maritime Geospatial Branch
8 Station Street, Wollongong
T: +61 2 4223 6506 | M: +61 434 349 674

Defence Intelligence Group | Department of Defence
[AGO Logo2]

IMPORTANT: This email remains the property of the Department of Defence. Unauthorised communication and dealing with the information in the email may be a serious criminal offence. If you have received this email in error, you are requested to contact the sender and delete the email immediately.

**Comment by mikan66** [comment]
From Alvaro: Consider all dredged areas as ‘Maintained’ (quality of vertical measurement = 10) unless the encoder consciously populates the quality of vertical measurement as 11 (not regularly maintained).
Consequently I propose the following portrayal logic:

- [ ] · Use Italics 

- [ ] · For qualityOfVerticalMeasurement = 10 (maintained depth) or Unknown or empty display the depth followed by the letter ‘m’ (i.e. 9.1m) 

- [ ] · For ‘not regularly maintained depths (qualityOfVerticalMeasurement = 11) display the text ‘dredged to’ followed by the depth, the letter ‘m’ and the ‘date in brackets’ when populated (i.e. dredged to 9.1m (2022)). 

- [ ] If dredgedDate is empty or Unknown then display the text ‘dredged to’ followed by the depth, the letter ‘m’ (i.e. dredged to 9.1m).

**Comment by KlasOstergren-SMA** [comment]
Alvaro:
I would propose that features with an empty qualityOfVerticalMeasurement is handled the other way around, meaning that features as not is stated to be maintained should be handled as not maintained. If a HO know that the area is regulary maintained, then qualityOfVerticalMeasurement will be set to maintained but if the HO does not have any information about the maintenance regime, they will probably set qualityOfVerticalMeasurement to empty/unknown. For me it would therefore be a "better safe than sorry solution" to treat features with an empty qualityOfVerticalMeasurement as not maintained.

**Comment by alvarosanuy** [comment]
Hi Klas, agree that it's all a bit confusing as national practices do not help with standardization. My take is ;  I imagine that if you were to populate **qualityOfVerticalMeasurement** as empty/Unknown, then you would do the same with **dredgedDate**. My question then is, how would you map that ENC encoding to your paper chart. In S-4, dredged depths without a date in brackets should be considered, by mariners, as maintained depths. Only when a date is encoded next to the depth, mariners should take additional care because the 'dredged to' depth shown is only true for the year in brackets and depth differences should be expected as times goes by (the longer the date gap the larger the depth difference).
Accordingly, the initial conversions from paper to ENC (S-57) should have been done under this premise. New dredged areas reported to HOs should come with (or the HO should seek) information on the maintenance regime in order to populate a meaningful **qualityOfVerticalMeasurement** (QUASOU) value. Worst case scenario, if the authority does not provide this info (hopefully the exception and not the rule), my view is that HOs should chart the dredged area as not maintained and populate **dredgedDate** using the reported date. In short, an ENC with only **depthRangeMinimumValue** (qualityOfVerticalMeasurement=empty/Unknown and no dredgedDate) populated, would most probably map to a depth value on the paper chart (i.e _9.1m_). According to S-4, this depiction indicates a 'maintained depth'. In my eyes, and in order to maintain consistency between ENC and paper charts, a dredged area carrying only depth info should be treated as a 'maintained dredged area'.

**OTHER VIEWS PLEASE !!**   :)

**Comment by KlasOstergren-SMA** [comment]
> My question then is, how would you map that ENC encoding to your paper chart. In S-4, dredged depths without a date in brackets should be considered, by mariners, as maintained depths.
> 

Our national practice is as follows:
Dredged areas that is maintained by SMA (where we actually know that the maintenance is working): Depth + QUASOU=Maintained, no SORDAT
Other dregded areas (for example in ports): Depth + SORDAT (year of the latest survey)

I agree that for the mapping between ENC's and paper charts, the date is the only information that can indicate if the area is regulary maintained or not. Of that reason, the use of QUASOU is actually not necessarily since the use of SORDAT (or not) tell the system/user the same information.
Therefore, we maybe should ignore the qualityOfVerticalMeasurement for the portrayal rules and propose to the DCEG sub-group to remove qualityOfVerticalMeasurement 10 and 11?

**Comment by alvarosanuy** [comment]
For PC version 1.0.2 lets go with:

- [ ] Use Italics

- [ ] When **depthRangeMinimumValue** is populated with a value <> Unknown - display the depth followed by the letter ‘m’ (i.e. 9.1m). This is irrespective of the value of **qualityOfVerticalMeasurement** [ 10 (maintained depth), 11 (not regularly maintained), Unknown or empty] 

- [ ] When **dredgedDate** is populated with a value - display the depth, the letter ‘m’ and the ‘date in brackets’ [i.e. 9.1m (2022)  ].
- [ ] If **dredgedDate** is populated and **depthRangeMinimumValue** = Unknown - no portrayal is to be generated.
 
Mariners will have to rely on 'Pick report' to learn the Dredged Area maintenance regime (if provided by the producer).

**Comment by mikan66** [comment]
see commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/d7880d7e6df545c1482dc6397a45836b21277bf8
