### ISSUE TITLE
Flare Angle (row 51 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#62]
![image](https://user-images.githubusercontent.com/4913543/167470499-ba34a54c-adb6-441c-a984-898bb9afdb59.png)

Rule Update Note: Sanchez, Alvaro MR:
"System" attribute, intended to be automatically populated by the production system (and can be over-ridden by the compiler) where there are two or more co-located all-around lights.  Required by portrayal to remove the requirement of a conditional symbology procedure.
LightFlareAndDescription rule exists but does not contain any special instructions to manage this attribute value

Need more info.

**Comment by alvarosanuy** [comment]
OFFICIAL
Hi Mikan,

This attribute is defined as an ECDIS ‘System’ (Portrayal) attribute, and DCEG section 30.2 (below) seems to indicate that flareAngle will be populated, in the feature itself, by the ENC production software (either automatically or with user intervention (??)) to improve readability when certain lights are collocated

The key thing here is for the ECDIS to recognise this attribute value and use it to override the default flare angle (045®) value. My understanding is that, in S-52, this was all managed by CSP(LIGHTS06) but it has now been ‘transferred’ to the compilation software/user (?)

Does this have any impact on the LightFlareAndDescription rule? I’m happy to cross this entry out from the master spreadsheet otherwise.


***@***.***


Alvaro

Alvaro Sanchez | Acting Director National Charting
Australian Hydrographic Office | Maritime Geospatial Branch
8 Station Street, Wollongong
T: +61 2 4223 6506 | M: +61 434 349 674

Defence Intelligence Group | Department of Defence
[AGO Logo2]

IMPORTANT: This email remains the property of the Department of Defence. Unauthorised communication and dealing with the information in the email may be a serious criminal offence. If you have received this email in error, you are requested to contact the sender and delete the email immediately.


From: mikan66 ***@***.***>
Sent: Tuesday, 10 May 2022 4:07 AM
To: iho-ohi/S-101_Portrayal-Catalogue ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iho-ohi/S-101_Portrayal-Catalogue] Flare Angle (row 51 main) (Issue #62)


 ⚠  EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.  ⚠.

[image]<https://user-images.githubusercontent.com/4913543/167470499-ba34a54c-adb6-441c-a984-898bb9afdb59.png>

Need more info.

**Comment by mikan66** [comment]
There are no restrictions in the Lua rules.  We can leave "as is" or introduce flareAngle in whichever part of the rule it is desired.    Right now, it looks for co-located features with COLOUR 1,6, or 11 and 'LightAllAround', 'LightAirObstruction', 'LightFogDetector'.  If found, then the flare is set to 45.  Please advise further.

**Comment by alvarosanuy** [comment]
From Mikan's comment it looks like the rule replicates S-52 and there's no need for production software to do the same. @JeffWootton Should we amend the wording in DCEG 2.4.5.1 ??
What is clear to me now is that **flareAngle** is not an attribute that HO's will see in the production tools. Therefore they won't have the option to select a random flare angle value.

**Comment by KlasOstergren-SMA** [comment]
From my point of view, I would prefere if the wording in 2.4.5.1 was changed to allow a wider use of the flareAngle attribute. As we all know, there are room for a lot of improvements in the ENC's to improve the readability. Today, the readability is often bad in narrow passages or archepelago areas where there are a lot of information in a small area. To improve the readability the flareAngle attribute could be used together with the other cartographic improvements in S-101 (like text placements and customised sector line length) to give the user a better view of the ENC. 
I understand that the current wording is written to solve a (former?) technical problem but this solution could be used to even improve the ENC's. I know that @JeffWootton has this noted to be discussed within the DCEG sub-group.

**Comment by DavidGrant-NIWC** [comment]
In MIkan's example both lights have _flareAngle_ set to 45, and the CSP also puts both flares at 45.

We will update the CSP to use _flareAngle_ when present, otherwise it will use the S-52 CSP logic.

![image](https://user-images.githubusercontent.com/62906211/178162636-622d1b95-b4b9-41e0-bf40-957ea84a90e2.png)
